return {
  "nvim-tree/nvim-web-devicons", -- Icon support for Nvim plugins
  config = function()
    require("nvim-web-devicons").set_icon({
      gql = { -- GraphQL
        icon = "",
        color = "#e535ab",
        cterm_color = "199",
        name = "GraphQL",
      },
      graphql = { -- GraphQL
        icon = "",
        color = "#e535ab",
        cterm_color = "199",
        name = "GraphQL",
      },
      ts = { -- TypeScript
        icon = "",
        color = "#007acc",
        cterm_color = "25",
        name = "TypeScript",
      },
      tsx = { -- TypeScript React
        icon = "",
        color = "#007acc",
        cterm_color = "25",
        name = "TypeScriptReact",
      },
      js = { -- JavaScript
        icon = "",
        color = "#f0db4f",
        cterm_color = "221",
        name = "JavaScript",
      },
      jsx = { -- JavaScript React
        icon = "",
        color = "#f0db4f",
        cterm_color = "221",
        name = "JavaScriptReact",
      },
      rs = { -- Rust
        icon = "",
        color = "#dea584",
        cterm_color = "180",
        name = "Rust",
      },
      rb = { -- Ruby
        icon = "",
        color = "#701516",
        cterm_color = "52",
        name = "Ruby",
      },
      py = { -- Python
        icon = "",
        color = "#3572a5",
        cterm_color = "24",
        name = "Python",
      },
      go = { -- Go
        icon = "",
        color = "#00add8",
        cterm_color = "38",
        name = "Go",
      },
      php = { -- PHP
        icon = "",
        color = "#4f5d95",
        cterm_color = "57",
        name = "PHP",
      },
      java = { -- Java
        icon = "",
        color = "#b07219",
        cterm_color = "130",
        name = "Java",
      },
      c = { -- C
        icon = "",
        color = "#555555",
        cterm_color = "239",
        name = "C",
      },
      cpp = { -- C Plus Plus
        icon = "",
        color = "#f34b7d",
        cterm_color = "168",
        name = "CPP",
      },
      h = { -- Header
        icon = "",
        color = "#555555",
        cterm_color = "239",
        name = "Header",
      },
      hpp = { -- Header
        icon = "",
        color = "#f34b7d",
        cterm_color = "168",
        name = "Header",
      },
      lua = { -- Lua
        icon = "",
        color = "#202099",
        cterm_color = "20",
        name = "Lua",
      },
      sh = { -- Shell
        icon = "",
        color = "#89e051",
        cterm_color = "71",
        name = "Shell",
      },
      zsh = { -- Zsh
        icon = "",
        color = "#89e051",
        cterm_color = "71",
        name = "Zsh",
      },
      bash = { -- Bash
        icon = "",
        color = "#89e051",
        cterm_color = "71",
        name = "Bash",
      },
      fish = { -- Fish
        icon = "",
        color = "#89e051",
        cterm_color = "71",
        name = "Fish",
      },
      vim = { -- Vim
        icon = "",
        color = "#019833",
        cterm_color = "71",
        name = "Vim",
      },
      vimrc = { -- Vim
        icon = "",
        color = "#019833",
        cterm_color = "71",
        name = "Vim",
      },
      nvim = { -- Neovim
        icon = "",
        color = "#57a143",
        cterm_color = "71",
        name = "Neovim",
      },
      nvimrc = { -- Neovim
        icon = "",
        color = "#57a143",
        cterm_color = "71",
        name = "Neovim",
      },
      html = { -- HTML
        icon = "",
        color = "#e34c26",
        cterm_color = "166",
        name = "HTML",
      },
      css = { -- CSS
        icon = "",
        color = "#563d7c",
        cterm_color = "57",
        name = "CSS",
      },
      scss = { -- SCSS
        icon = "",
        color = "#c6538c",
        cterm_color = "168",
        name = "SCSS",
      },
      sass = { -- SASS
        icon = "",
        color = "#c6538c",
        cterm_color = "168",
        name = "SASS",
      },
      less = { -- LESS
        icon = "",
        color = "#1d365d",
        cterm_color = "24",
        name = "LESS",
      },
      json = { -- JSON
        icon = "",
        color = "#fedf3b",
        cterm_color = "0",
        name = "JSON",
      },
      yaml = { -- YAML
        icon = "",
        color = "#fedf3b",
        cterm_color = "0",
        name = "YAML",
      },
      toml = { -- TOML
        icon = "",
        color = "#fedf3b",
        cterm_color = "0",
        name = "TOML",
      },
      md = { -- Markdown
        icon = "󰽛",
        color = "#519aba",
        cterm_color = "38",
        name = "Markdown",
      },
      mdx = { -- Markdown MDX
        icon = "󰽛",
        color = "#519aba",
        cterm_color = "38",
        name = "MarkdownMDX",
      },
      txt = { -- Text
        icon = "",
        color = "#fedf3b",
        cterm_color = "0",
        name = "Text",
      },
      conf = { -- Config
        icon = "",
        color = "#fedf3b",
        cterm_color = "0",
        name = "Config",
      },
      ini = { -- INI
        icon = "",
        color = "#fedf3b",
        cterm_color = "0",
        name = "INI",
      },
      gitconfig = { -- Git Config
        icon = "",
        color = "#f03c2e",
        cterm_color = "0",
        name = "GitConfig",
      },
      gitignore = { -- Git Ignore
        icon = "",
        color = "#f03c2e",
        cterm_color = "0",
        name = "GitIgnore",
      },
      gitattributes = { -- Git Attributes
        icon = "",
        color = "#f03c2e",
        cterm_color = "0",
        name = "GitAttributes",
      },
      gitmodules = { -- Git Modules
        icon = "",
        color = "#f03c2e",
        cterm_color = "0",
        name = "GitModules",
      },
      dockerfile = { -- Dockerfile
        icon = "",
        color = "#384d54",
        cterm_color = "59",
        name = "Dockerfile",
      },
      dockerignore = { -- Dockerignore
        icon = "",
        color = "#384d54",
        cterm_color = "59",
        name = "Dockerignore",
      },
      makefile = { -- Makefile
        icon = "",
        color = "#427819",
        cterm_color = "22",
        name = "Makefile",
      },
      rakefile = { -- Rakefile
        icon = "",
        color = "#427819",
        cterm_color = "22",
        name = "Rakefile",
      },
      rake = { -- Rakefile
        icon = "",
        color = "#427819",
        cterm_color = "22",
        name = "Rakefile",
      },
      raketask = { -- Rakefile
        icon = "",
        color = "#427819",
        cterm_color = "22",
        name = "Rakefile",
      },
      zshrc = {
        icon = "",
        color = "#89e051",
        cterm_color = "71",
        name = "Zsh",
      },
      zshenv = {
        icon = "",
        color = "#89e051",
        cterm_color = "71",
        name = "Zsh",
      },
      ["vimrc.lua"] = {
        icon = "",
        color = "#019833",
        cterm_color = "71",
        name = "Vim",
      },
      ["init.vim"] = {
        icon = "",
        color = "#019833",
        cterm_color = "71",
        name = "Vim",
      },
      ["init.lua"] = {
        icon = "",
        color = "#019833",
        cterm_color = "71",
        name = "Vim",
      },
      ["lua.lua"] = {
        icon = "",
        color = "#000080",
        cterm_color = "20",
        name = "Lua",
      },
      ["lua.vim"] = {
        icon = "",
        color = "#000080",
        cterm_color = "20",
        name = "Lua",
      },
      ["lua.vimrc"] = {
        icon = "",
        color = "#000080",
        cterm_color = "20",
        name = "Lua",
      },
      ["lua.init.vim"] = {
        icon = "",
        color = "#000080",
        cterm_color = "20",
        name = "Lua",
      },
      ["lua.init.lua"] = {
        icon = "",
        color = "#000080",
        cterm_color = "20",
        name = "Lua",
      },
      ["lua.config.lua"] = {
        icon = "",
        color = "#000080",
        cterm_color = "20",
        name = "Lua",
      },
      ["lua.config.vim"] = {
        icon = "",
        color = "#000080",
        cterm_color = "20",
        name = "Lua",
      },
      ["lua.config.vimrc"] = {
        icon = "",
        color = "#000080",
        cterm_color = "20",
        name = "Lua",
      },
    })
  end,
}
